// <auto-generated />
namespace WSExample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201411200309039_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
